service: crud-users

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "dynamodb:*"
          Resource: "arn:aws:dynamodb:us-east-1:469286914666:table/usersTable"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      # noStart: true     # Uncomment only if you already have a DynamoDB running locally
    seed:
      domain:
        sources:
          - table: usersTable
            sources: [./db/usersTable.json]
  
functions:
  get-user:
    handler: src/functions/getUsers/handler.getUsers
    package:
      patterns:
        - "src/functions/getUsers/handler.js"
    events:
      - http:
          path: user/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  create-users:
    handler: src/functions/createUser/handler.create_user
    runtime: python3.8
    package:
      patterns:
        - "src/functions/createUser/handler.py"
    events:
      - http:
          path: users
          method: POST
  update-user:
    handler: src/functions/updateUser/handler.update_user
    runtime: python3.8
    package:
      patterns:
        - "src/functions/updateUser/handler.py"
    events:
      - http:
          path: users/{id}
          method: PATCH
          request:
            parameters:
              paths:
                id: true
  delete-user:
    handler: src/functions/deleteUser/handler.delete_user
    runtime: python3.8
    package:
      patterns:
        - "src/functions/deleteUser/handler.py"
    events:
      - http:
          path: users/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1